name: LucasPreti
favicon: null
layout_spectrum: 0.24149
typography_spectrum: 0.95769
title: 'Lucas Preti website '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d4d4'
    - '#76a5d4'
    - '#3f5068'
    - '#000001'
    - '#fdc500'
  brandStrength: 0.375
  lightness: 0.2349001243710518
  saturation: 0.30860677920281887
  rhythmicContrast: 0.9990904454607517
purpose: []
