name: LucasPreti
favicon: null
layout_spectrum: 0.24149
typography_spectrum: 0.95769
title: 'Lucas Preti website '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#5f6269'
    - '#2e3235'
    - '#fefefe'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.2349001243710518
  saturation: 0.30860677920281887
  rhythmicContrast: 0.25
purpose: []
