name: LucasPreti
favicon: null
layout_spectrum: 0.6574560960289091
typography_spectrum: 0.8547729116398841
title: 'Lucas Preti AI website '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3378841858357191
  lightness: 0.2349001243710518
  saturation: 0.30860677920281887
  rhythmicContrast: 0.9990904454607517
purpose: []
