name: LucasPreti
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58701
title: 'Lucas Preti website '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#5f6269'
    - '#2e3235'
    - '#fefefe'
    - '#808080'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
